<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmgr3bi\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmgr3bi/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHmgr3bi.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerHmgr3bi\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerHmgr3bi\EccubeProdProjectContainer([
    'container.build_hash' => 'Hmgr3bi',
    'container.build_id' => '6fbd55dd',
    'container.build_time' => 1615346537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmgr3bi');
